const CACHE_NAME = 'ipray-v202509231745';
const urlsToCache = [
  '/i-pray/',
  '/i-pray/index.html',
  '/i-pray/alhamisi1.html',
  '/i-pray/alhamisi2.html',
  '/i-pray/alhamisi3.html',
  '/i-pray/alhamisi4.html',
  '/i-pray/amefufuka.html',
  '/i-pray/antifona.html',
  '/i-pray/calendar.html',
  '/i-pray/carmen.html',
  '/i-pray/fallback.html',
  '/i-pray/holy-rosary.html',
  '/i-pray/ijumaa1.html',
  '/i-pray/ijumaa2.html',
  '/i-pray/ijumaa3.html',
  '/i-pray/ijumaa4.html',
  '/i-pray/index.html',
  '/i-pray/jumamosi1.html',
  '/i-pray/jumamosi2.html',
  '/i-pray/jumamosi3.html',
  '/i-pray/jumamosi4.html',
  '/i-pray/jumanne1.html',
  '/i-pray/jumanne2.html',
  '/i-pray/jumanne3.html',
  '/i-pray/jumanne4.html',
  '/i-pray/jumapili1.html',
  '/i-pray/jumapili2.html',
  '/i-pray/jumapili3.html',
  '/i-pray/jumapili4.html',
  '/i-pray/jumatano1.html',
  '/i-pray/jumatano2.html',
  '/i-pray/jumatano3.html',
  '/i-pray/jumatano4.html',
  '/i-pray/jumatatu1.html',
  '/i-pray/jumatatu2.html',
  '/i-pray/jumatatu3.html',
  '/i-pray/jumatatu4.html',
  '/i-pray/lauds.html',
  '/i-pray/main.css',
  '/i-pray/manifest.json',
  '/i-pray/mwaka-week11.html',
  '/i-pray/mwaka-week12.html',
  '/i-pray/mwaka1.html',
  '/i-pray/mwaka2-week11.html',
  '/i-pray/mwaka2-week12.html',
  '/i-pray/mwaka2-week13.html',
  '/i-pray/mwaka2-week14.html',
  '/i-pray/mwaka2-week15.html',
  '/i-pray/mwaka2-week16.html',
  '/i-pray/mwaka2-week17.html',
  '/i-pray/mwaka2-week18.html',
  '/i-pray/mwaka2-week19.html',
  '/i-pray/mwaka2-week20.html',
  '/i-pray/mwaka2.html',
  '/i-pray/mwaka3-week21.html',
  '/i-pray/mwaka3-week22.html',
  '/i-pray/mwaka3-week23.html',
  '/i-pray/mwaka3-week24.html',
  '/i-pray/mwaka3-week25.html',
  '/i-pray/mwaka3-week26.html',
  '/i-pray/mwaka3-week27.html',
  '/i-pray/mwaka3-week28.html',
  '/i-pray/mwaka3-week29.html',
  '/i-pray/mwaka3-week30.html',
  '/i-pray/mwaka3-week31.html',
  '/i-pray/mwaka3-week32.html',
  '/i-pray/mwaka3-week33.html',
  '/i-pray/mwaka3-week34.html',
  '/i-pray/mwaka3.html',
  '/i-pray/MwakaSehemu2.txt',
  '/i-pray/package-lock.json',
  '/i-pray/package.json',
  '/i-pray/postcss.config.js',
  '/i-pray/prayer.html',
  '/i-pray/sacraments.html',
  '/i-pray/service-worker.js',
  '/i-pray/settings.html',
  '/i-pray/tailwind.config.js',
  '/i-pray/theme-manager.js',
  '/i-pray/assets/august/10aug.html',
  '/i-pray/assets/august/11aug.html',
  '/i-pray/assets/august/12aug.html',
  '/i-pray/assets/august/13aug.html',
  '/i-pray/assets/august/14aug.html',
  '/i-pray/assets/august/15aug.html',
  '/i-pray/assets/august/16aug.html',
  '/i-pray/assets/august/17aug.html',
  '/i-pray/assets/august/18aug.html',
  '/i-pray/assets/august/19aug.html',
  '/i-pray/assets/august/1aug.html',
  '/i-pray/assets/august/20aug.html',
  '/i-pray/assets/august/21aug.html',
  '/i-pray/assets/august/22aug.html',
  '/i-pray/assets/august/23aug.html',
  '/i-pray/assets/august/24aug.html',
  '/i-pray/assets/august/25aug.html',
  '/i-pray/assets/august/26aug.html',
  '/i-pray/assets/august/27aug.html',
  '/i-pray/assets/august/28aug.html',
  '/i-pray/assets/august/29aug.html',
  '/i-pray/assets/august/2aug.html',
  '/i-pray/assets/august/30aug.html',
  '/i-pray/assets/august/31aug.html',
  '/i-pray/assets/august/3aug.html',
  '/i-pray/assets/august/4aug.html',
  '/i-pray/assets/august/5aug.html',
  '/i-pray/assets/august/6aug.html',
  '/i-pray/assets/august/7aug.html',
  '/i-pray/assets/august/8aug.html',
  '/i-pray/assets/august/9aug.html',
  '/i-pray/assets/css/styles.css',
  '/i-pray/assets/icons/icon-144x144.png',
  '/i-pray/assets/icons/icon-192x192.png',
  '/i-pray/assets/icons/icon-512x512.png',
  '/i-pray/assets/icons/icon-72x72.png',
  '/i-pray/assets/icons/icon-96x96.png',
  '/i-pray/assets/icons/icons.json',
  '/i-pray/assets/icons/android/android-launchericon-48-48.png',
  '/i-pray/assets/icons/ios/100.png',
  '/i-pray/assets/icons/ios/1024.png',
  '/i-pray/assets/icons/ios/114.png',
  '/i-pray/assets/icons/ios/120.png',
  '/i-pray/assets/icons/ios/128.png',
  '/i-pray/assets/icons/ios/144.png',
  '/i-pray/assets/icons/ios/152.png',
  '/i-pray/assets/icons/ios/16.png',
  '/i-pray/assets/icons/ios/167.png',
  '/i-pray/assets/icons/ios/180.png',
  '/i-pray/assets/icons/ios/192.png',
  '/i-pray/assets/icons/ios/20.png',
  '/i-pray/assets/icons/ios/256.png',
  '/i-pray/assets/icons/ios/29.png',
  '/i-pray/assets/icons/ios/32.png',
  '/i-pray/assets/icons/ios/40.png',
  '/i-pray/assets/icons/ios/50.png',
  '/i-pray/assets/icons/ios/512.png',
  '/i-pray/assets/icons/ios/57.png',
  '/i-pray/assets/icons/ios/58.png',
  '/i-pray/assets/icons/ios/60.png',
  '/i-pray/assets/icons/ios/64.png',
  '/i-pray/assets/icons/ios/72.png',
  '/i-pray/assets/icons/ios/76.png',
  '/i-pray/assets/icons/ios/80.png',
  '/i-pray/assets/icons/ios/87.png',
  '/i-pray/assets/icons/windows11/LargeTile.scale-100.png',
  '/i-pray/assets/icons/windows11/LargeTile.scale-125.png',
  '/i-pray/assets/icons/windows11/LargeTile.scale-150.png',
  '/i-pray/assets/icons/windows11/LargeTile.scale-200.png',
  '/i-pray/assets/icons/windows11/LargeTile.scale-400.png',
  '/i-pray/assets/icons/windows11/SmallTile.scale-100.png',
  '/i-pray/assets/icons/windows11/SmallTile.scale-125.png',
  '/i-pray/assets/icons/windows11/SmallTile.scale-150.png',
  '/i-pray/assets/icons/windows11/SmallTile.scale-200.png',
  '/i-pray/assets/icons/windows11/SmallTile.scale-400.png',
  '/i-pray/assets/icons/windows11/SplashScreen.scale-100.png',
  '/i-pray/assets/icons/windows11/SplashScreen.scale-125.png',
  '/i-pray/assets/icons/windows11/SplashScreen.scale-150.png',
  '/i-pray/assets/icons/windows11/SplashScreen.scale-200.png',
  '/i-pray/assets/icons/windows11/SplashScreen.scale-400.png',
  '/i-pray/assets/icons/windows11/Square150x150Logo.scale-100.png',
  '/i-pray/assets/icons/windows11/Square150x150Logo.scale-125.png',
  '/i-pray/assets/icons/windows11/Square150x150Logo.scale-150.png',
  '/i-pray/assets/icons/windows11/Square150x150Logo.scale-200.png',
  '/i-pray/assets/icons/windows11/Square150x150Logo.scale-400.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-16.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-20.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-24.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-256.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-30.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-32.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-36.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-40.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-44.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-48.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-60.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-64.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-72.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-80.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-96.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-unplated_targetsize-16.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-unplated_targetsize-20.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-unplated_targetsize-24.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-unplated_targetsize-256.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-unplated_targetsize-30.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-unplated_targetsize-32.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-unplated_targetsize-36.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-unplated_targetsize-40.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-unplated_targetsize-44.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-unplated_targetsize-48.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-unplated_targetsize-60.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-unplated_targetsize-64.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-unplated_targetsize-72.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-unplated_targetsize-80.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.altform-unplated_targetsize-96.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.scale-100.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.scale-125.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.scale-150.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.scale-200.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.scale-400.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.targetsize-16.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.targetsize-20.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.targetsize-24.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.targetsize-256.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.targetsize-30.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.targetsize-32.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.targetsize-36.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.targetsize-40.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.targetsize-44.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.targetsize-48.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.targetsize-60.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.targetsize-64.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.targetsize-72.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.targetsize-80.png',
  '/i-pray/assets/icons/windows11/Square44x44Logo.targetsize-96.png',
  '/i-pray/assets/icons/windows11/StoreLogo.scale-100.png',
  '/i-pray/assets/icons/windows11/StoreLogo.scale-125.png',
  '/i-pray/assets/icons/windows11/StoreLogo.scale-150.png',
  '/i-pray/assets/icons/windows11/StoreLogo.scale-200.png',
  '/i-pray/assets/icons/windows11/StoreLogo.scale-400.png',
  '/i-pray/assets/icons/windows11/Wide310x150Logo.scale-100.png',
  '/i-pray/assets/icons/windows11/Wide310x150Logo.scale-125.png',
  '/i-pray/assets/icons/windows11/Wide310x150Logo.scale-150.png',
  '/i-pray/assets/icons/windows11/Wide310x150Logo.scale-200.png',
  '/i-pray/assets/icons/windows11/Wide310x150Logo.scale-400.png',
  '/i-pray/assets/images/bikira maria.jpg',
  '/i-pray/assets/images/bikira wa pentekoste.jpg',
  '/i-pray/assets/images/Camino_Neocatecumenal_Carmen_Hernandez-OG.jpg',
  '/i-pray/assets/images/Carmen baracas.jpg',
  '/i-pray/assets/images/carmen-hernandez- grave.jpg',
  '/i-pray/assets/images/carmen-hernandez-camino.jpg',
  '/i-pray/assets/images/carmen.jpg',
  '/i-pray/assets/images/Carmen_Casimiro_Morcillo_Barracas_Madrid.jpg',
  '/i-pray/assets/images/familia takatifu.jpg',
  '/i-pray/assets/images/favicon.ico.jpg',
  '/i-pray/assets/images/icon-192x192.png',
  '/i-pray/assets/images/icon-512x512.png',
  '/i-pray/assets/images/maria mdogo.png',
  '/i-pray/assets/images/unsplash-photo-1.jpg',
  '/i-pray/assets/images/unsplash-photo-2.jpg',
  '/i-pray/assets/july/31jul.html',
  '/i-pray/assets/october/10oct.html',
  '/i-pray/assets/october/11oct.html',
  '/i-pray/assets/october/12oct.html',
  '/i-pray/assets/october/13oct.html',
  '/i-pray/assets/october/14oct.html',
  '/i-pray/assets/october/15oct.html',
  '/i-pray/assets/october/16oct.html',
  '/i-pray/assets/october/17oct.html',
  '/i-pray/assets/october/18oct.html',
  '/i-pray/assets/october/19oct.html',
  '/i-pray/assets/october/1oct.html',
  '/i-pray/assets/october/20oct.html',
  '/i-pray/assets/october/2oct.html',
  '/i-pray/assets/october/3oct.html',
  '/i-pray/assets/october/4oct.html',
  '/i-pray/assets/october/5oct.html',
  '/i-pray/assets/october/6oct.html',
  '/i-pray/assets/october/7oct.html',
  '/i-pray/assets/october/8oct.html',
  '/i-pray/assets/october/9oct.html',
  '/i-pray/assets/readings/fri18.html',
  '/i-pray/assets/readings/fri19.html',
  '/i-pray/assets/readings/fri20.html',
  '/i-pray/assets/readings/fri21.html',
  '/i-pray/assets/readings/fri22.html',
  '/i-pray/assets/readings/mon18.html',
  '/i-pray/assets/readings/mon19.html',
  '/i-pray/assets/readings/mon20.html',
  '/i-pray/assets/readings/mon21.html',
  '/i-pray/assets/readings/mon22.html',
  '/i-pray/assets/readings/sat18.html',
  '/i-pray/assets/readings/sat19.html',
  '/i-pray/assets/readings/sat20.html',
  '/i-pray/assets/readings/sat21.html',
  '/i-pray/assets/readings/sun18.html',
  '/i-pray/assets/readings/sun19.html',
  '/i-pray/assets/readings/sun21.html',
  '/i-pray/assets/readings/sun22.html',
  '/i-pray/assets/readings/thur18.html',
  '/i-pray/assets/readings/thur19.html',
  '/i-pray/assets/readings/thur21.html',
  '/i-pray/assets/readings/thur22.html',
  '/i-pray/assets/readings/tue18.html',
  '/i-pray/assets/readings/tue19.html',
  '/i-pray/assets/readings/tue20.html',
  '/i-pray/assets/readings/tue21.html',
  '/i-pray/assets/readings/tue22.html',
  '/i-pray/assets/readings/wed 20.html',
  '/i-pray/assets/readings/wed18.html',
  '/i-pray/assets/readings/wed19.html',
  '/i-pray/assets/readings/wed21.html',
  '/i-pray/assets/readings/wed22.html',
  '/i-pray/assets/readings/office/Mass-Readings-August-2025-PDF-Download.pdf',
  '/i-pray/assets/readings/office/Mass-Readings-December-2025-PDF-Download.pdf',
  '/i-pray/assets/readings/office/Mass-Readings-November-2025-PDF-Download.pdf',
  '/i-pray/assets/readings/office/Mass-Readings-October-2025-PDF-Download.pdf',
  '/i-pray/assets/readings/office/Mass-Readings-September-2025-PDF-Download.pdf',
  '/i-pray/assets/september/10sep.html',
  '/i-pray/assets/september/11sep.html',
  '/i-pray/assets/september/12sep.html',
  '/i-pray/assets/september/13sep.html',
  '/i-pray/assets/september/14sep.html',
  '/i-pray/assets/september/15sep.html',
  '/i-pray/assets/september/16sep.html',
  '/i-pray/assets/september/17sep.html',
  '/i-pray/assets/september/18sep.html',
  '/i-pray/assets/september/19sep.html',
  '/i-pray/assets/september/1sep.html',
  '/i-pray/assets/september/20sep.html',
  '/i-pray/assets/september/21sep.html',
  '/i-pray/assets/september/22sep.html',
  '/i-pray/assets/september/23sep.html',
  '/i-pray/assets/september/24sep.html',
  '/i-pray/assets/september/25sep.html',
  '/i-pray/assets/september/26sep.html',
  '/i-pray/assets/september/27sep.html',
  '/i-pray/assets/september/28sep.html',
  '/i-pray/assets/september/29sep.html',
  '/i-pray/assets/september/2sep.html',
  '/i-pray/assets/september/30sep.html',
  '/i-pray/assets/september/3sep.html',
  '/i-pray/assets/september/4sep.html',
  '/i-pray/assets/september/5sep.html',
  '/i-pray/assets/september/6sep.html',
  '/i-pray/assets/september/7sep.html',
  '/i-pray/assets/september/8sep.html',
  '/i-pray/assets/september/9sep.html',
  '/i-pray/PDFS/advent 1.pdf',
  '/i-pray/PDFS/advent 2.pdf',
  '/i-pray/PDFS/advent 3.pdf',
  '/i-pray/PDFS/advent 4.pdf',
  '/i-pray/PDFS/amefufuka.pdf',
  '/i-pray/PDFS/christmas.pdf',
  '/i-pray/PDFS/comon saints.pdf',
  '/i-pray/PDFS/easter 1.pdf',
  '/i-pray/PDFS/easter 2.pdf',
  '/i-pray/PDFS/easter 3.pdf',
  '/i-pray/PDFS/easter 4.pdf',
  '/i-pray/PDFS/easter 5.pdf',
  '/i-pray/PDFS/easter 6.pdf',
  '/i-pray/PDFS/easter 7.pdf',
  '/i-pray/PDFS/lent 1.pdf',
  '/i-pray/PDFS/lent 2.pdf',
  '/i-pray/PDFS/lent 3.pdf',
  '/i-pray/PDFS/lent 4.pdf',
  '/i-pray/PDFS/lent 5.pdf',
  '/i-pray/PDFS/lent 6.pdf',
  '/i-pray/PDFS/lent.pdf',
  '/i-pray/PDFS/MajilioNaNoeli.pdf',
  '/i-pray/PDFS/MasifuYaAsubuhi.pdf',
  '/i-pray/PDFS/MwakaSehemu1.pdf',
  '/i-pray/PDFS/MwakaSehemu2.pdf',
  '/i-pray/PDFS/MwakaSehemu3.pdf',
  '/i-pray/PDFS/noel 1.pdf',
  '/i-pray/PDFS/noel 2.pdf',
  '/i-pray/PDFS/noel 3.pdf',
  '/i-pray/PDFS/ordinary 1.pdf',
  '/i-pray/PDFS/ordinary 10.pdf',
  '/i-pray/PDFS/ordinary 11.pdf',
  '/i-pray/PDFS/ordinary 12.pdf',
  '/i-pray/PDFS/ordinary 2.pdf',
  '/i-pray/PDFS/ordinary 24.pdf',
  '/i-pray/PDFS/ordinary 25.pdf',
  '/i-pray/PDFS/ordinary 26.pdf',
  '/i-pray/PDFS/ordinary 27.pdf',
  '/i-pray/PDFS/ordinary 28.pdf',
  '/i-pray/PDFS/ordinary 29.pdf',
  '/i-pray/PDFS/ordinary 3.pdf',
  '/i-pray/PDFS/ordinary 30.pdf',
  '/i-pray/PDFS/ordinary 31.pdf',
  '/i-pray/PDFS/ordinary 32.pdf',
  '/i-pray/PDFS/ordinary 33.pdf',
  '/i-pray/PDFS/ordinary 4.pdf',
  '/i-pray/PDFS/ordinary 5.pdf',
  '/i-pray/PDFS/ordinary 6.pdf',
  '/i-pray/PDFS/ordinary 7.pdf',
  '/i-pray/PDFS/ordinary 8.pdf',
  '/i-pray/PDFS/ordinary 9.pdf',
  '/i-pray/PDFS/pentecost.pdf',
  '/i-pray/PDFS/saints feb.pdf',
  '/i-pray/PDFS/saints jan.pdf',
  '/i-pray/PDFS/saints jun.pdf',
  '/i-pray/PDFS/solemnities.pdf',
  '/i-pray/PDFS/tinywow_V5034W_80795109.pdf',
  '/i-pray/scripts/dump-mwaka2-text.js',
  '/i-pray/scripts/generate-mwaka2-weeks.js',
  '/i-pray/src/input.css',
  '/i-pray/src/output.css'
];

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then(cache => {
        return cache.addAll(urlsToCache);
      })
  );
  self.skipWaiting();
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(cacheNames => {
      return Promise.all(
        cacheNames.map(cacheName => {
          if (cacheName !== CACHE_NAME) {
            return caches.delete(cacheName);
          }
        })
      );
    })
  );
  self.clients.claim();
});

self.addEventListener('fetch', event => {
  event.respondWith(
    caches.match(event.request)
      .then(response => {
        if (response) {
          return response;
        }
        return fetch(event.request).then(networkResponse => {
          // Cache mwaka3-week files on first access
          if (event.request.url.includes('/i-pray/mwaka3-week')) {
            const responseClone = networkResponse.clone();
            caches.open(CACHE_NAME).then(cache => {
              cache.put(event.request, responseClone);
            });
          }
          return networkResponse;
        });
      })
  );
});
